apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: openshift-gatekeeper-system
spec:
  match:
    - excludeNamespaces:
        - xxx
        - aaaaa
      processes:
        - '*'