apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: mybucket
      endpoint: s3.openshift-storage.svc:8080
      insecure: true
      access_key: THISISACCESSKEY
      secret_key: ThisIsSecretKeyThisIsSecretKey