apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ .Values.examplePolicy.name }}
  annotations:
    policy.open-cluster-management.io/standards: {{ .Values.examplePolicy.standards }}
    policy.open-cluster-management.io/categories: {{ .Values.examplePolicy.categories }}
    policy.open-cluster-management.io/controls: {{ .Values.examplePolicy.controls }}
spec:
  remediationAction: {{ .Values.examplePolicy.remediationAction }}
  disabled: {{ .Values.examplePolicy.disabled }}
  # One or Many Policy Templates
  #  policy creation now:
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespace-example
        spec:
          # the policy-template spec.remediationAction is overridden by the preceding parameter value for spec.remediationAction.
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude: ["kube-*"]
            include: ["default"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                # must have namespace 'prod'
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: prod