apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: image-policy
# ...omitted output...
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: image-policy
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Image
                metadata:
                  name: cluster
                spec:
                  registrySources:
                    allowedRegistries:
                      - image-registry.openshift-image-registry.svc:5000
                      - registry.redhat.io
                      - registry.access.redhat.com
                      - quay.io