apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ .Values.managedClusterName }}
  namespace: {{ .Values.managedClusterName }}
spec:
  managedClusterName: {{ .Values.managedClusterName }}
  managedClusterNamespace: {{ .Values.managedClusterName }}
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  version: {{ .Values.acmVersion }}